import { createHash, randomUUID } from "node:crypto";
import { mkdirSync, existsSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

/**
 * Files attached to a task - lecture slides, handouts.
 *
 * The bytes live beside the database (data/uploads) rather than inside it: a
 * term of slide decks would bloat the SQLite file, and every backup copies it
 * whole. The database holds only the record, and `storedName` is generated
 * here, so nothing a file is called can ever reach the filesystem.
 */

export const MAX_UPLOAD_BYTES = 40 * 1024 * 1024; // 40MB - a big slide deck
export const ALLOWED_MIME = ["application/pdf"];

/** Where the SQLite file lives; uploads sit next to it. */
export function dataDir(): string {
  const url = process.env.DATABASE_URL ?? "file:./prisma/dev.db";
  const file = url.replace(/^file:/, "");
  return dirname(resolve(file));
}

export function uploadsDir(): string {
  return join(dataDir(), "uploads");
}

export function uploadPath(storedName: string): string {
  // storedName is generated by this module, but resolve anyway so a bad row
  // can't walk out of the uploads folder.
  const path = resolve(join(uploadsDir(), storedName));
  if (!path.startsWith(resolve(uploadsDir()))) throw new Error("Bad upload path");
  return path;
}

export type SavedUpload = { storedName: string; size: number; sha: string };

/** Write bytes to the uploads folder under a generated name. */
export function saveUpload(bytes: Buffer, extension = "pdf"): SavedUpload {
  mkdirSync(uploadsDir(), { recursive: true });
  const storedName = `${randomUUID()}.${extension.replace(/[^a-z0-9]/gi, "").toLowerCase() || "bin"}`;
  writeFileSync(uploadPath(storedName), bytes);
  return {
    storedName,
    size: bytes.byteLength,
    sha: createHash("sha256").update(bytes).digest("hex").slice(0, 16),
  };
}

export function deleteUpload(storedName: string) {
  try {
    rmSync(uploadPath(storedName), { force: true });
  } catch {
    // A missing file is fine - the record is what matters.
  }
}

export function uploadExists(storedName: string): boolean {
  try {
    return existsSync(uploadPath(storedName)) && statSync(uploadPath(storedName)).isFile();
  } catch {
    return false;
  }
}

/** What's wrong with this upload, or null if it's fine. */
export function checkUpload(mime: string, size: number): string | null {
  if (!ALLOWED_MIME.includes(mime)) return "Only PDFs can be attached.";
  if (size <= 0) return "That file is empty.";
  if (size > MAX_UPLOAD_BYTES) return `That file is over ${Math.round(MAX_UPLOAD_BYTES / 1024 / 1024)}MB.`;
  return null;
}
